// Generated by CoffeeScript 1.4.0

/*
#
# Main JavaScript
#
*/


(function() {
  "use strict";

  if (!window.console) {
    window.console = {
      log: function() {}
    };
  }

  $(function() {
    return $("p, li, h1, h2, h3, h4, h5, h6, a, span").unorphan();
  });

}).call(this);
