markdown: maruku
pygments: true
permalink: pretty
exclude: [Cakefile, README.md, CNAME]
title: jShamsul.com (@jibone)
description: Personal website of J.Shamsul (@jibone), a full stack web developer based in Kuala Lumpur, Malaysia.
url: http://jshamsul.com
assets_url: http://assets.jshamsul.com
